use pyo3::prelude::*;
use pyo3::exceptions::PyValueError;

mod ast;
#[allow(clippy::all)]
mod spinach; // This will be generated by LALRPOP

#[pyclass]
pub struct Parser {}

#[pymethods]
impl Parser {
    #[new]
    fn new() -> Self {
        Parser {}
    }

    #[staticmethod]
    fn get_tree(code: &str) -> PyResult<String> {
        match spinach::StartParser::new().parse(code) {
            Ok(ast) => Ok(format!("{:#?}", ast)),
            Err(e) => Err(PyValueError::new_err(format!("Parse error: {}", e))),
        }
    }
}

#[pymodule]
fn spinach_parser(_py: Python, m: &PyModule) -> PyResult<()> {
    m.add_class::<Parser>()?;
    Ok(())
}
